### ISSUE TITLE
append/prepend conf files

### ISSUE THREAD

**Issue by suntong** [b4tman/docker-squid#10]
Hi Dmitry, 

I noticed that the current setting of `squid.conf` is:

```
$ diff -wU 1 squid.conf.default squid.conf
--- squid.conf.default  2019-08-06 09:34:21.000000000 -0400
+++ squid.conf  2019-08-06 09:34:30.000000000 -0400
@@ -76 +76,2 @@
 refresh_pattern .              0       20%     4320
+include /etc/squid/conf.d/*.conf
```

However, there are cases that settings need to be added to the front of `squid.conf`, e.g., when specifying squid authentication -- better put up front. Would you consider adding it please?

If so, I propose something like this:

```
$ diff -wU 1 squid.conf.default squid.conf
--- squid.conf.default  2019-08-06 09:34:21.000000000 -0400
+++ squid.conf  2019-08-08 17:35:37.239905486 -0400
@@ -1 +1,2 @@
+include /etc/squid/conf.d/front-*.conf
 #
@@ -76 +77,2 @@
 refresh_pattern .              0       20%     4320
+include /etc/squid/conf.d/rear-*.conf
```

The use of pair `front/rear` is the best I came up so far. E.g., if using `append/prepend`, then the file order would be wrong (those being appended are showing in the front when doing `ls`). The pair `begin/end` is OK by the order, but I was looking for a prefix pair that of similar length  (if not the same). 

Please consider. 
Thanks!

**Comment by suntong** [comment]
> The use of pair front/rear is the best I came up so far.

Ah, I've got a better idea -- for prepend, use `include /etc/squid/conf.d/[0-4]*.conf`, and for append, use `[5-9]*.conf`.

How is that?

**Comment by b4tman** [comment]
Hi,
Good idea, thanks for suggestion!

**Comment by b4tman** [comment]
> Ah, I've got a better idea -- for prepend, use `include /etc/squid/conf.d/[0-4]*.conf`, and for append, use `[5-9]*.conf`.
> 
> How is that?

Unfortunately, did not work.

I added separate folders:
- `conf.d` - for prepend
- `conf.d.tail` - for append

**Comment by suntong** [comment]
Oh..., 

> I added separate folders

Like that! :+1:
