### ISSUE TITLE
Enabling SNMP in Squid for Monitoring with Cacti

### ISSUE THREAD

**Issue by huangchao-shanghai** [b4tman/docker-squid#107]
I intend to use Cacti to monitor the status of Squid via SNMP. However, it seems that SNMP is not enabled by default in Squid. Can you provide instructions on how to enable SNMP?

**Comment by b4tman** [comment]
Hi, @huangchao-shanghai!

Here squid docs: https://wiki.squid-cache.org/Features/Snmp.
To enable SNMP support you need to set [snmp_port](http://www.squid-cache.org/Doc/config/snmp_port/) configuration directive. But it requires `--enable-snmp` build option ([here](https://github.com/b4tman/docker-squid/blob/2d0d3bd90c105f044acb264ca5362f3c56e47ce6/Dockerfile#L89)).

I'll try to add this to the `latest` image.
