### ISSUE TITLE
Mutli-arch builds no longer being built on DockerHub?

### ISSUE THREAD

**Issue by Vorsku** [b4tman/docker-squid#27]
Hi,

Thanks for this project - I was just wondering why the `latest` tag is only built for amd64 - I'm trying to run this on a RPI swarm and it's failing as it's not built for ARM

I tried pulling the `armhf` tag which works, however it hasn't been updated for 2 years so the Squid/Alpine versions are out of date.

Thanks!

**Comment by b4tman** [comment]
Hello! Thank you for the question! 
I need some help to configure multiarch builds on dockerhub. 
Earlier I used to build the armhf tag manually on a raspberry pi, but now I don't have one. 

Also i tried to build armhf image on dockerhub using quemu (armhf-cross tag), but it's very slow, so builds is failing becouse of very long build time. 

I will try to update armhf and armhf-cross tags.

**Comment by Vorsku** [comment]
@b4tman thanks! Is there any way I can help? I have a Swarm of RPI2's which are perfect for armhf - I could build the releases for you on the `armhf` tag if you don't have the hardware anymore?
