### ISSUE TITLE
kerberos auth

### ISSUE THREAD

**Issue by codingfunwoody** [b4tman/docker-squid#28]
why do you enable negotiate wrapper auth but doesn't enable kerberos auth? The build image doesn't enable it. Afterwards image can't use the kerberos auth. Btw, thanks for your effort you are the only one to keep update the squid docker image.

**Comment by b4tman** [comment]
Thanks!

I had some compilation errors on older versions with kerberos auth enabled.
Just forgot to check it in newer versions, sorry.

I will enable it soon.
