### ISSUE TITLE
build error on arm64 

### ISSUE THREAD

**Issue by endlessbest** [b4tman/docker-squid#77]
this is a nice repo i have used for one year, but after upgrading my raspberry pi to 64bit OS, it's not supported. so i start to build this docker image by tag v4.16.0, this is a good version for me.  here is the build error: 
`
 > [linux/arm64 build  9/11] RUN set -x &&      cd /tmp/build &&        nproc=$(n=$(nproc) ; max_n=6 ; [ $n -le $max_n ] && echo $n || echo $max_n) &&  make -j $nproc && make install &&  cd tools/squidclient && make && make install-strip:
#17 0.083 + cd /tmp/build
#17 0.090 + nproc
#17 0.105 + n=2
#17 0.106 + max_n=6
#17 0.108 + '[' 2 -le 6 ]
#17 0.113 + echo 2
#17 0.116 + nproc=2
#17 0.117 + make -j 2
#17 0.217 Making all in compat
#17 0.271 make[1]: Entering directory '/tmp/build/compat'
#17 0.291   CXX      assert.lo
#17 0.294   CXX      compat.lo
#17 2.194   CXX      debug.lo
#17 2.664   CC       eui64_aton.lo
#17 4.217   CXX      getaddrinfo.lo
#17 4.996   CXX      getnameinfo.lo
#17 6.198   CC       GnuRegex.lo
#17 6.942   CXX      inet_ntop.lo
#17 7.684   CXX      inet_pton.lo
#17 8.981   CXX      memrchr.lo
#17 9.695   CXX      shm.lo
#17 10.96   CXX      statvfs.lo
#17 12.12   CXX      strnstr.lo
#17 12.91   CC       strnrchr.lo
#17 15.05   CXX      xalloc.lo
#17 15.21   CXX      xstrerror.lo
#17 17.98   CXX      xstring.lo
#17 17.99   CXX      xstrto.lo
#17 21.04   CXX      mswindows.lo
#17 22.90   CXXLD    libcompatsquid.la
#17 24.93 make[1]: Leaving directory '/tmp/build/compat'
#17 24.93 Making all in lib
#17 24.99 make[1]: Entering directory '/tmp/build/lib'
#17 25.05 Making all in ntlmauth
#17 25.10 make[2]: Entering directory '/tmp/build/lib/ntlmauth'
#17 25.12   CXX      ntlmauth.lo
#17 33.70   CXXLD    libntlmauth.la
#17 34.73 make[2]: Leaving directory '/tmp/build/lib/ntlmauth'
#17 34.79 make[2]: Entering directory '/tmp/build/lib'
#17 34.81   CC       base64.lo
#17 34.81   CC       charset.lo
#17 37.14   CC       html_quote.lo
#17 38.52   CC       md5.lo
#17 39.86   CC       rfc1738.lo
#17 42.32   CC       rfc2617.lo
#17 43.13   CXX      hash.lo
#17 45.46   CC       getfullhostname.lo
#17 47.75   CC       heap.lo
#17 48.10   CC       iso3307.lo
#17 50.79   CC       radix.lo
#17 51.84   CC       rfc1123.lo
#17 55.05   CXX      Splay.lo
#17 57.10   CC       stub_memaccount.lo
#17 58.38   CC       util.lo
#17 59.06   CC       xusleep.lo
#17 61.38   CCLD     libmiscencoding.la
#17 61.49   CXXLD    libmisccontainers.la
#17 62.64   CXXLD    libmiscutil.la
#17 64.16 make[2]: Leaving directory '/tmp/build/lib'
#17 64.17 make[1]: Leaving directory '/tmp/build/lib'
#17 64.17 Making all in libltdl
#17 64.24 make[1]: Entering directory '/tmp/build/libltdl'
#17 64.29   GEN      libltdl/lt__argz.h
#17 64.32 make  all-am
#17 64.39 make[2]: Entering directory '/tmp/build/libltdl'
#17 64.47   CC       libltdlc_la-lt__alloc.lo
#17 64.48 Error while loading /usr/local/sbin/mkdir: No such file or directory
#17 64.48 make[2]: *** [Makefile:624: loaders/.deps/.dirstamp] Error 1
#17 64.48 make[2]: *** Waiting for unfinished jobs....
#17 66.17 make[2]: Leaving directory '/tmp/build/libltdl'
#17 66.17 make[1]: *** [Makefile:522: all] Error 2
#17 66.17 make[1]: Leaving directory '/tmp/build/libltdl'
#17 66.18 make: *** [Makefile:588: all-recursive] Error 1
`
please help, thx.

**Comment by endlessbest** [comment]
i tried to tweak Dockerfile a little bit, the 'mkdir' issue is gone, there is my fix:
line 100:
`
RUN set -x && \
	cd /tmp/build && mkdir -p /usr/local/sbin/ && ln -sf /bin/mkdir /usr/local/sbin/mkdir && \
	nproc=$(n=$(nproc) ; max_n=6 ; [ $n -le $max_n ] && echo $n || echo $max_n) && \
	make -j $nproc && \
	make install && \
	cd tools/squidclient && make && make install-strip
`

but get stucked here: 

`
#17 4922.8  ../../../../cfgaux/install-sh -c -d '/usr/lib/squid'
#17 4923.0   /bin/sh ../../../../libtool   --mode=install /usr/bin/install -c basic_getpwnam_auth '/usr/lib/squid'
#17 4923.2 libtool: install: /usr/bin/install -c basic_getpwnam_auth /usr/lib/squid/basic_getpwnam_auth
#17 4923.2  ../../../../cfgaux/install-sh -c -d '/usr/share/man/man8'
#17 4923.4  /usr/bin/install -c -m 644 basic_getpwnam_auth.8 '/usr/share/man/man8'
#17 4923.4 make[6]: Leaving directory '/tmp/build/src/auth/basic/getpwnam'
#17 4923.4 make[5]: Leaving directory '/tmp/build/src/auth/basic/getpwnam'
#17 4923.4 Making install in NCSA
#17 4923.4 make[5]: Entering directory '/tmp/build/src/auth/basic/NCSA'
#17 4923.5 make[6]: Entering directory '/tmp/build/src/auth/basic/NCSA'
#17 4923.5  ../../../../cfgaux/install-sh -c -d '/usr/lib/squid'
#17 4923.6   /bin/sh ../../../../libtool   --mode=install /usr/bin/install -c basic_ncsa_auth '/usr/lib/squid'
#17 4923.9 libtool: install: /usr/bin/install -c basic_ncsa_auth /usr/lib/squid/basic_ncsa_auth
#17 4923.9  ../../../../cfgaux/install-sh -c -d '/usr/share/man/man8'
#17 4924.0  /usr/bin/install -c -m 644 basic_ncsa_auth.8 '/usr/share/man/man8'
#17 4924.1 make[6]: Leaving directory '/tmp/build/src/auth/basic/NCSA'
#17 4924.1 make[5]: Leaving directory '/tmp/build/src/auth/basic/NCSA'
#17 4924.1 make[5]: Entering directory '/tmp/build/src/auth/basic'
#17 4924.2 make[6]: Entering directory '/tmp/build/src/auth/basic'
#17 4924.2 make[6]: Nothing to be done for 'install-exec-am'.
#17 4924.2 make[6]: Nothing to be done for 'install-data-am'.
#17 4924.2 make[6]: Leaving directory '/tmp/build/src/auth/basic'
#17 4924.2 make[5]: Leaving directory '/tmp/build/src/auth/basic'
#17 4924.2 make[4]: Leaving directory '/tmp/build/src/auth/basic'
#17 4924.2 Making install in digest
#17 4924.2 make[4]: Entering directory '/tmp/build/src/auth/digest'
#17 4924.3 Making install in file
#17 4924.4 make[5]: Entering directory '/tmp/build/src/auth/digest/file'
#17 4924.5 make[6]: Entering directory '/tmp/build/src/auth/digest/file'
#17 4924.5  ../../../../cfgaux/install-sh -c -d '/usr/lib/squid'
#17 4924.5 Assertion failed: p_rcu_reader->depth != 0 (/qemu/include/qemu/rcu.h: rcu_read_unlock: 101)
#17 4924.6 Aborted (core dumped)
#17 4924.6 make[6]: *** [Makefile:801: install-libexecPROGRAMS] Error 1
#17 4924.6 make[6]: Leaving directory '/tmp/build/src/auth/digest/file'
#17 4924.6 make[5]: *** [Makefile:1197: install-am] Error 2
#17 4924.6 make[5]: Leaving directory '/tmp/build/src/auth/digest/file'
#17 4924.6 make[4]: *** [Makefile:891: install-recursive] Error 1
#17 4924.6 make[4]: Leaving directory '/tmp/build/src/auth/digest'
#17 4924.6 make[3]: *** [Makefile:934: install-recursive] Error 1
#17 4924.6 make[3]: Leaving directory '/tmp/build/src/auth'
#17 4924.6 make[2]: *** [Makefile:7129: install-recursive] Error 1
#17 4924.6 make[2]: Leaving directory '/tmp/build/src'
#17 4924.6 make[1]: *** [Makefile:7657: install] Error 2
#17 4924.6 make[1]: Leaving directory '/tmp/build/src'
#17 4924.6 make: *** [Makefile:588: install-recursive] Error 1
`

i have no idea of how to get over with it

**Comment by b4tman** [comment]
Hi @endlessbest.

I successfully built v4.16 on arm64 via [cloud.drone.io](https://github.com/b4tman/docker-squid/commit/cf4b3f4845a54387913672b6195e501f4a4e4d09) (native build, without qemu), images pushed to: 
- docker.io/b4tman/squid:4.16.1-arm64 and
- ghcr.io/b4tman/squid-arm64:4.16.1

---

> Error while loading /usr/local/sbin/mkdir: No such file or directory

not sure about this error
seems like file system problem
try updating docker or:

~~~sh
docker image rm alpine:3.14.0
docker pull alpine:3.14.0
~~~

---

> Assertion failed: p_rcu_reader->depth != 0 (/qemu/include/qemu/rcu.h: rcu_read_unlock: 101)

seems like qemu issue, are you using [emulation](https://www.docker.com/blog/multi-platform-docker-builds/) or building on native arm64 machine?

**Comment by endlessbest** [comment]
> 

thank you so much for the help, then i don't have to build it myself. 

> seems like qemu issue, are you using [emulation](https://www.docker.com/blog/multi-platform-docker-builds/) or building on native arm64 machine?
yes, emulation.

**Comment by endlessbest** [comment]
it works again for the raspberry pi 4  64bit, thanks for the quick response. have a good day.
